### ISSUE TITLE
Version inofrmation of psubst.bat

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ildar-shaimordanov/psubst#11]
```
I want to suggest to put the information of the file version with an "echo" for 
exemple...

Thank you a lot.

```

Original issue reported on code.google.com by `jpa...@gmail.com` on 18 Sep 2014 at 9:55

**Comment by ildar-shaimordanov** [comment]
Closed in the recent release 2.6.2 https://github.com/ildar-shaimordanov/psubst/releases/tag/v2.6.2
