### ISSUE TITLE
Does not work after Windows Anniversary update

### ISSUE THREAD

**Issue by manuelbieh** [ildar-shaimordanov/psubst#13]
Looks like support for Dos Devices has been dropped in Windows Anniversary :confused:

**Comment by ildar-shaimordanov** [comment]
@manuelbieh, thank you for update. Sad to know this. Could you provide more details on this issue, please? Most probably, the source of this knowledge, versions of the operating system, service pack or something else would be useful.

**Comment by beppe9000** [comment]
I used psubst successfully on Microsoft Windows 10 Pro x64 Version 1607 Build 14393.

**Comment by cyotek** [comment]
Just wanted to add my own comment regarding Anniversary update - I didn't use `psubst` directly, but I did come across this repository when searching for "windows persist subst", and created a reg file using the Inconstancy section of your readme. After rebooting there was my virtual drive - no apparent problems there. I'm also on the Anniversary update, same version as the previous posted.

**Comment by ildar-shaimordanov** [comment]
Thanks every one for your feedbacks. There seems no issue with Windows Anniversary update. I suppose this is usability issue -- most probably no access for writing to Windows Registry or rebooting is required. I am closing the issue.

**Comment by beppe9000** [comment]
Maybe a check for that could be added ?
