### ISSUE TITLE
Peristent needs administrator

### ISSUE THREAD

**Issue by speich** [ildar-shaimordanov/psubst#15]
When I call from the console as user:
`psubst H: \\vboxsrv\images /P`
I get:
`ERROR: Access denied`
The virtual drive is created anyway, but the registry is not set.
If I run the psubst command as administrator, it works but only for user administrator. How do I make it work for my normal user?

**Comment by ildar-shaimordanov** [comment]
@speich 

Thank you for your feedback. Right now I don't have any ideas how to solve the issue. Most probably in the future I will look into this. What I can say the script is not developed to work with network devices and I have never tested it with them. Most probably you need the more relevant command ;like `net share`.

**Comment by speich** [comment]
Ok, I look into `net use`. Thanks for the hint.

**Comment by mwerle** [comment]
@speich : Give the user(s) that need to be able to set persistent path write-access to the following Registry key: `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices`

To do so, open _regedit_, navigate to the key, right-click on it, and select "Permissions". It's similar to setting permissions on a file or directory.

**Comment by ildar-shaimordanov** [comment]
I explained this issue in the page https://github.com/ildar-shaimordanov/psubst/blob/master/IssuesAndTroubleshooting.md#peristent-needs-administrator.

**Comment by ildar-shaimordanov** [comment]
I implemented setting the persistent drives with elevated privileges. Please try [Version 3.0.0 Beta](https://github.com/ildar-shaimordanov/psubst/releases/tag/v3.0.0-beta)

**Comment by ildar-shaimordanov** [comment]
The stable version [Version 3.0.1 Stable](https://github.com/ildar-shaimordanov/psubst/releases/tag/v3.0.1) is available
