### ISSUE TITLE
Merge Cyberponk branch

### ISSUE THREAD

**Issue by AlexanderWillner** [ildar-shaimordanov/psubst#17]
See subject and https://github.com/cyberponk/psubst

**Comment by ildar-shaimordanov** [comment]
Hi Alexander,

Sorry for too late response. I can't remember how has it happened that I missed your comment. 

To be honest, cyberpronk's version of the tool is not the same as mine. His tool implements some additional features out of the scope of the original idea. It is more complicated and codes are not compatible.

**Comment by ildar-shaimordanov** [comment]
@AlexanderWillner , you could be interested that the new release was issued. Finally it supports elevated privileges for creating persistent drives.

**Comment by AlexanderWillner** [comment]
👍
