### ISSUE TITLE
Use SUBST when defining a new drive so the reboot won't be immediately required to begin using the new drive

### ISSUE THREAD

**Issue by al20878** [ildar-shaimordanov/psubst#23]
It looks like defining a new drive with this script requires a reboot for the registry setting to take effect (while regular SUBST'ed drives are available right away).  Suggested is to use SUBST, in addition, with the same command line arguments so that the new drive becomes immediately accessible (and will later persist through the reboot via the registry setting).
Thanks for considering.

**Comment by ildar-shaimordanov** [comment]
@al20878, thank you for your interest to this tool.

You can run the script twice: the first time for persisting a drive and the second one for using it immediately:

~~~
psubst h: "%USERPROFILE%" /p
psubst h: "%USERPROFILE%"
~~~

Probably you'll need elevated privileges with the `/pf` option instead '`/p` in the first command.

I guess it's not explained enough and README is required to be rewrited. Later I'll do this.

**Comment by al20878** [comment]
I thought that one command should do one thing as making a new drive available.  I don't need a second invocation of "psubst" to make the drive ready right away, the standard "subst" would do it just fine for me, followed by "psubst" with "/P" if I wanted to make that assignment permanent.  Anyways, it's not an issue per se, was just a mere suggestion.  Thanks for your prompt response, though.
